### ISSUE TITLE
Allow static methods.

### ISSUE THREAD

**Issue by ticki** [durka/unborrow#2]
Nice crate! Unfortunately, there is an annoying limitation: No lonely method (the token `::` isn't expected).

```
error: no rules expected the token `::`
   --> src/block.rs:160:22
    |
160 |         unborrow!(mem::replace(self, Block::empty(self.ptr.clone())));
    |                      ^^
```

**Comment by durka** [comment]
Hmm, good point.  I'll look into whether this can be supported.

**Comment by ticki** [comment]
BTW, you should really promote this on /r/rust. It's a very useful crate!

**Comment by durka** [comment]
Well, I already shamelessly plug it whenever it's relevant in answering a question :)

**Comment by durka** [comment]
How do you think this would work? Should it just assume the first parameter is the `&mut` one and the rest should be pre-evaluated? It's a bit less clear-cut than the object method case.

**Comment by ticki** [comment]
Yeah, that was what I thought (`mem::replace` is the biggest one I guess).

**Comment by ticki** [comment]
Cool
